# fly.toml app configuration file generated for kora-server on 2024-12-23T14:09:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kora-server'
primary_region = 'bos'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Add this section for custom domain
[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/health-check"
  min_consecutive_successes = 2
  max_consecutive_failures = 3

# Add your custom domain
[http_service.domains]
  hostnames = ["api.materials.nyc"]

[deploy]
  strategy = "rolling"

# Add database connection check
[[services.checks]]
  grace_period = "30s"
  interval = "30s"
  timeout = "10s"
  type = "startup"
  command = "python manage.py check"
