# Generated by Django 5.0.1 on 2024-12-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_issue_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=8),
        ),
    ]
