# Generated by Django 5.0.1 on 2024-12-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_issue_options_alter_issue_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productidea',
            options={},
        ),
        migrations.RenameField(
            model_name='productidea',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productidea',
            old_name='idea',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='productidea',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='productidea',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='productidea',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productidea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
